ui_infer_args = {'gpu_device': 0,
                 'colab': False,
                 'loop_smpl': 100,
                 'patience': 5,
                 'vis_freq': 1000,
                 'loop_cloth': 200,
                 'hps_type': 'pymaf',
                 'export_video': False,
                 'in_dir': './test_images',
                 'out_dir': './results',
                 'seg_dir': None,
                 'config': 'configs/configsv1.yaml',
                 'mlpSe': True,
                 'mlpSev1': False,
                 'mlpSemax': False,
                 'mlp3d': False,
                 'conv3d_start': 2,
                 'conv3d_kernelsize': 1,
                 'pad_mode': 'zeros',
                 'mlp_first_dim': 0,
                 'uncertainty': False,
                 'beta_min': 0.03,
                 'beta_plus': 3.0,
                 'barf_c2f': [0.1, 0.5],
                 'kernel_pad_num': '10',
                 'mlp_pad_mode': 'zeros',
                 'smpl_attention': True,
                 'filter': True,
                 'adaptive_pe_sdf': True,
                 'use_clip': False,
                 'clip_fuse_layer': '23',
                 'triplane': False,
                 'train_on_cape': False,
                 'sdfdir': False,
                 'pamir_vol_dim': 6,
                 'PE_sdf': 14,
                 'se_start_channel': 1,
                 'se_end_channel': 3,
                 'se_reduction': 4,
                 'cse': False,
                 'sse': True,
                 'use_unet': False,
                 'mlp_dim': [13, 512, 256, 128, 1],
                 'res_layers': [2, 3, 4],
                 'expname': 'infer_in_the_wild',
                 'ckpt_path': './ckpt/last.ckpt',
                 'dropout': 0,
                 'perturb_sdf': 0,
                 'pamir_icon': True
                 }
